// Code generated by capnpc-go. DO NOT EDIT.

package cpnp

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
)

type Player capnp.Struct

// Player_TypeID is the unique identifier for the type Player.
const Player_TypeID = 0xc8a5b9936b00d9a4

func NewPlayer(s *capnp.Segment) (Player, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return Player(st), err
}

func NewRootPlayer(s *capnp.Segment) (Player, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return Player(st), err
}

func ReadRootPlayer(msg *capnp.Message) (Player, error) {
	root, err := msg.Root()
	return Player(root.Struct()), err
}

func (s Player) String() string {
	str, _ := text.Marshal(0xc8a5b9936b00d9a4, capnp.Struct(s))
	return str
}

func (s Player) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Player) DecodeFromPtr(p capnp.Ptr) Player {
	return Player(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Player) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Player) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Player) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Player) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Player) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Player) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Player) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Player) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Player) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Player) HasName() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Player) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Player) SetName(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Player) X() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s Player) SetX(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s Player) Y() int32 {
	return int32(capnp.Struct(s).Uint32(4))
}

func (s Player) SetY(v int32) {
	capnp.Struct(s).SetUint32(4, uint32(v))
}

// Player_List is a list of Player.
type Player_List = capnp.StructList[Player]

// NewPlayer creates a new list of Player.
func NewPlayer_List(s *capnp.Segment, sz int32) (Player_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[Player](l), err
}

// Player_Future is a wrapper for a Player promised by a client call.
type Player_Future struct{ *capnp.Future }

func (f Player_Future) Struct() (Player, error) {
	p, err := f.Future.Ptr()
	return Player(p.Struct()), err
}

type GameBroadcastConnect capnp.Struct

// GameBroadcastConnect_TypeID is the unique identifier for the type GameBroadcastConnect.
const GameBroadcastConnect_TypeID = 0x8d79563191b5ff43

func NewGameBroadcastConnect(s *capnp.Segment) (GameBroadcastConnect, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return GameBroadcastConnect(st), err
}

func NewRootGameBroadcastConnect(s *capnp.Segment) (GameBroadcastConnect, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return GameBroadcastConnect(st), err
}

func ReadRootGameBroadcastConnect(msg *capnp.Message) (GameBroadcastConnect, error) {
	root, err := msg.Root()
	return GameBroadcastConnect(root.Struct()), err
}

func (s GameBroadcastConnect) String() string {
	str, _ := text.Marshal(0x8d79563191b5ff43, capnp.Struct(s))
	return str
}

func (s GameBroadcastConnect) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GameBroadcastConnect) DecodeFromPtr(p capnp.Ptr) GameBroadcastConnect {
	return GameBroadcastConnect(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GameBroadcastConnect) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GameBroadcastConnect) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GameBroadcastConnect) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GameBroadcastConnect) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GameBroadcastConnect) Player() (Player, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Player(p.Struct()), err
}

func (s GameBroadcastConnect) HasPlayer() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GameBroadcastConnect) SetPlayer(v Player) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewPlayer sets the player field to a newly
// allocated Player struct, preferring placement in s's segment.
func (s GameBroadcastConnect) NewPlayer() (Player, error) {
	ss, err := NewPlayer(capnp.Struct(s).Segment())
	if err != nil {
		return Player{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s GameBroadcastConnect) Connected() bool {
	return capnp.Struct(s).Bit(0)
}

func (s GameBroadcastConnect) SetConnected(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

// GameBroadcastConnect_List is a list of GameBroadcastConnect.
type GameBroadcastConnect_List = capnp.StructList[GameBroadcastConnect]

// NewGameBroadcastConnect creates a new list of GameBroadcastConnect.
func NewGameBroadcastConnect_List(s *capnp.Segment, sz int32) (GameBroadcastConnect_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[GameBroadcastConnect](l), err
}

// GameBroadcastConnect_Future is a wrapper for a GameBroadcastConnect promised by a client call.
type GameBroadcastConnect_Future struct{ *capnp.Future }

func (f GameBroadcastConnect_Future) Struct() (GameBroadcastConnect, error) {
	p, err := f.Future.Ptr()
	return GameBroadcastConnect(p.Struct()), err
}
func (p GameBroadcastConnect_Future) Player() Player_Future {
	return Player_Future{Future: p.Future.Field(0, nil)}
}

type GameBroadcastChat capnp.Struct

// GameBroadcastChat_TypeID is the unique identifier for the type GameBroadcastChat.
const GameBroadcastChat_TypeID = 0xf8ed6301e876b572

func NewGameBroadcastChat(s *capnp.Segment) (GameBroadcastChat, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return GameBroadcastChat(st), err
}

func NewRootGameBroadcastChat(s *capnp.Segment) (GameBroadcastChat, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return GameBroadcastChat(st), err
}

func ReadRootGameBroadcastChat(msg *capnp.Message) (GameBroadcastChat, error) {
	root, err := msg.Root()
	return GameBroadcastChat(root.Struct()), err
}

func (s GameBroadcastChat) String() string {
	str, _ := text.Marshal(0xf8ed6301e876b572, capnp.Struct(s))
	return str
}

func (s GameBroadcastChat) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GameBroadcastChat) DecodeFromPtr(p capnp.Ptr) GameBroadcastChat {
	return GameBroadcastChat(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GameBroadcastChat) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GameBroadcastChat) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GameBroadcastChat) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GameBroadcastChat) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GameBroadcastChat) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s GameBroadcastChat) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GameBroadcastChat) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s GameBroadcastChat) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s GameBroadcastChat) Text() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s GameBroadcastChat) HasText() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s GameBroadcastChat) TextBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s GameBroadcastChat) SetText(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// GameBroadcastChat_List is a list of GameBroadcastChat.
type GameBroadcastChat_List = capnp.StructList[GameBroadcastChat]

// NewGameBroadcastChat creates a new list of GameBroadcastChat.
func NewGameBroadcastChat_List(s *capnp.Segment, sz int32) (GameBroadcastChat_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[GameBroadcastChat](l), err
}

// GameBroadcastChat_Future is a wrapper for a GameBroadcastChat promised by a client call.
type GameBroadcastChat_Future struct{ *capnp.Future }

func (f GameBroadcastChat_Future) Struct() (GameBroadcastChat, error) {
	p, err := f.Future.Ptr()
	return GameBroadcastChat(p.Struct()), err
}

type GameBroadcastPlayerMove capnp.Struct

// GameBroadcastPlayerMove_TypeID is the unique identifier for the type GameBroadcastPlayerMove.
const GameBroadcastPlayerMove_TypeID = 0x8e5205afc0f14fe0

func NewGameBroadcastPlayerMove(s *capnp.Segment) (GameBroadcastPlayerMove, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return GameBroadcastPlayerMove(st), err
}

func NewRootGameBroadcastPlayerMove(s *capnp.Segment) (GameBroadcastPlayerMove, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return GameBroadcastPlayerMove(st), err
}

func ReadRootGameBroadcastPlayerMove(msg *capnp.Message) (GameBroadcastPlayerMove, error) {
	root, err := msg.Root()
	return GameBroadcastPlayerMove(root.Struct()), err
}

func (s GameBroadcastPlayerMove) String() string {
	str, _ := text.Marshal(0x8e5205afc0f14fe0, capnp.Struct(s))
	return str
}

func (s GameBroadcastPlayerMove) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GameBroadcastPlayerMove) DecodeFromPtr(p capnp.Ptr) GameBroadcastPlayerMove {
	return GameBroadcastPlayerMove(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GameBroadcastPlayerMove) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GameBroadcastPlayerMove) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GameBroadcastPlayerMove) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GameBroadcastPlayerMove) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GameBroadcastPlayerMove) Who() (Player, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Player(p.Struct()), err
}

func (s GameBroadcastPlayerMove) HasWho() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GameBroadcastPlayerMove) SetWho(v Player) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewWho sets the who field to a newly
// allocated Player struct, preferring placement in s's segment.
func (s GameBroadcastPlayerMove) NewWho() (Player, error) {
	ss, err := NewPlayer(capnp.Struct(s).Segment())
	if err != nil {
		return Player{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// GameBroadcastPlayerMove_List is a list of GameBroadcastPlayerMove.
type GameBroadcastPlayerMove_List = capnp.StructList[GameBroadcastPlayerMove]

// NewGameBroadcastPlayerMove creates a new list of GameBroadcastPlayerMove.
func NewGameBroadcastPlayerMove_List(s *capnp.Segment, sz int32) (GameBroadcastPlayerMove_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[GameBroadcastPlayerMove](l), err
}

// GameBroadcastPlayerMove_Future is a wrapper for a GameBroadcastPlayerMove promised by a client call.
type GameBroadcastPlayerMove_Future struct{ *capnp.Future }

func (f GameBroadcastPlayerMove_Future) Struct() (GameBroadcastPlayerMove, error) {
	p, err := f.Future.Ptr()
	return GameBroadcastPlayerMove(p.Struct()), err
}
func (p GameBroadcastPlayerMove_Future) Who() Player_Future {
	return Player_Future{Future: p.Future.Field(0, nil)}
}

type GameServerGarbage capnp.Struct

// GameServerGarbage_TypeID is the unique identifier for the type GameServerGarbage.
const GameServerGarbage_TypeID = 0xd3f2426b260480f4

func NewGameServerGarbage(s *capnp.Segment) (GameServerGarbage, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return GameServerGarbage(st), err
}

func NewRootGameServerGarbage(s *capnp.Segment) (GameServerGarbage, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return GameServerGarbage(st), err
}

func ReadRootGameServerGarbage(msg *capnp.Message) (GameServerGarbage, error) {
	root, err := msg.Root()
	return GameServerGarbage(root.Struct()), err
}

func (s GameServerGarbage) String() string {
	str, _ := text.Marshal(0xd3f2426b260480f4, capnp.Struct(s))
	return str
}

func (s GameServerGarbage) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GameServerGarbage) DecodeFromPtr(p capnp.Ptr) GameServerGarbage {
	return GameServerGarbage(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GameServerGarbage) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GameServerGarbage) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GameServerGarbage) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GameServerGarbage) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GameServerGarbage) Amount() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s GameServerGarbage) SetAmount(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s GameServerGarbage) Per() uint8 {
	return capnp.Struct(s).Uint8(4)
}

func (s GameServerGarbage) SetPer(v uint8) {
	capnp.Struct(s).SetUint8(4, v)
}

func (s GameServerGarbage) Base() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s GameServerGarbage) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GameServerGarbage) BaseBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s GameServerGarbage) SetBase(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// GameServerGarbage_List is a list of GameServerGarbage.
type GameServerGarbage_List = capnp.StructList[GameServerGarbage]

// NewGameServerGarbage creates a new list of GameServerGarbage.
func NewGameServerGarbage_List(s *capnp.Segment, sz int32) (GameServerGarbage_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[GameServerGarbage](l), err
}

// GameServerGarbage_Future is a wrapper for a GameServerGarbage promised by a client call.
type GameServerGarbage_Future struct{ *capnp.Future }

func (f GameServerGarbage_Future) Struct() (GameServerGarbage, error) {
	p, err := f.Future.Ptr()
	return GameServerGarbage(p.Struct()), err
}

type GameServerPlayers capnp.Struct

// GameServerPlayers_TypeID is the unique identifier for the type GameServerPlayers.
const GameServerPlayers_TypeID = 0xaaccfc7400a32fc1

func NewGameServerPlayers(s *capnp.Segment) (GameServerPlayers, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return GameServerPlayers(st), err
}

func NewRootGameServerPlayers(s *capnp.Segment) (GameServerPlayers, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return GameServerPlayers(st), err
}

func ReadRootGameServerPlayers(msg *capnp.Message) (GameServerPlayers, error) {
	root, err := msg.Root()
	return GameServerPlayers(root.Struct()), err
}

func (s GameServerPlayers) String() string {
	str, _ := text.Marshal(0xaaccfc7400a32fc1, capnp.Struct(s))
	return str
}

func (s GameServerPlayers) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GameServerPlayers) DecodeFromPtr(p capnp.Ptr) GameServerPlayers {
	return GameServerPlayers(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GameServerPlayers) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GameServerPlayers) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GameServerPlayers) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GameServerPlayers) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GameServerPlayers) Players() (Player_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Player_List(p.List()), err
}

func (s GameServerPlayers) HasPlayers() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GameServerPlayers) SetPlayers(v Player_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewPlayers sets the players field to a newly
// allocated Player_List, preferring placement in s's segment.
func (s GameServerPlayers) NewPlayers(n int32) (Player_List, error) {
	l, err := NewPlayer_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Player_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// GameServerPlayers_List is a list of GameServerPlayers.
type GameServerPlayers_List = capnp.StructList[GameServerPlayers]

// NewGameServerPlayers creates a new list of GameServerPlayers.
func NewGameServerPlayers_List(s *capnp.Segment, sz int32) (GameServerPlayers_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[GameServerPlayers](l), err
}

// GameServerPlayers_Future is a wrapper for a GameServerPlayers promised by a client call.
type GameServerPlayers_Future struct{ *capnp.Future }

func (f GameServerPlayers_Future) Struct() (GameServerPlayers, error) {
	p, err := f.Future.Ptr()
	return GameServerPlayers(p.Struct()), err
}

type GameClientChat capnp.Struct

// GameClientChat_TypeID is the unique identifier for the type GameClientChat.
const GameClientChat_TypeID = 0x92ebca0fa2bbe017

func NewGameClientChat(s *capnp.Segment) (GameClientChat, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return GameClientChat(st), err
}

func NewRootGameClientChat(s *capnp.Segment) (GameClientChat, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return GameClientChat(st), err
}

func ReadRootGameClientChat(msg *capnp.Message) (GameClientChat, error) {
	root, err := msg.Root()
	return GameClientChat(root.Struct()), err
}

func (s GameClientChat) String() string {
	str, _ := text.Marshal(0x92ebca0fa2bbe017, capnp.Struct(s))
	return str
}

func (s GameClientChat) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GameClientChat) DecodeFromPtr(p capnp.Ptr) GameClientChat {
	return GameClientChat(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GameClientChat) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GameClientChat) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GameClientChat) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GameClientChat) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GameClientChat) Text() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s GameClientChat) HasText() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GameClientChat) TextBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s GameClientChat) SetText(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// GameClientChat_List is a list of GameClientChat.
type GameClientChat_List = capnp.StructList[GameClientChat]

// NewGameClientChat creates a new list of GameClientChat.
func NewGameClientChat_List(s *capnp.Segment, sz int32) (GameClientChat_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[GameClientChat](l), err
}

// GameClientChat_Future is a wrapper for a GameClientChat promised by a client call.
type GameClientChat_Future struct{ *capnp.Future }

func (f GameClientChat_Future) Struct() (GameClientChat, error) {
	p, err := f.Future.Ptr()
	return GameClientChat(p.Struct()), err
}

type GameClientMoved capnp.Struct

// GameClientMoved_TypeID is the unique identifier for the type GameClientMoved.
const GameClientMoved_TypeID = 0xe5874bdd3e613cd0

func NewGameClientMoved(s *capnp.Segment) (GameClientMoved, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return GameClientMoved(st), err
}

func NewRootGameClientMoved(s *capnp.Segment) (GameClientMoved, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return GameClientMoved(st), err
}

func ReadRootGameClientMoved(msg *capnp.Message) (GameClientMoved, error) {
	root, err := msg.Root()
	return GameClientMoved(root.Struct()), err
}

func (s GameClientMoved) String() string {
	str, _ := text.Marshal(0xe5874bdd3e613cd0, capnp.Struct(s))
	return str
}

func (s GameClientMoved) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GameClientMoved) DecodeFromPtr(p capnp.Ptr) GameClientMoved {
	return GameClientMoved(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GameClientMoved) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GameClientMoved) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GameClientMoved) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GameClientMoved) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GameClientMoved) X() int8 {
	return int8(capnp.Struct(s).Uint8(0))
}

func (s GameClientMoved) SetX(v int8) {
	capnp.Struct(s).SetUint8(0, uint8(v))
}

func (s GameClientMoved) Y() int8 {
	return int8(capnp.Struct(s).Uint8(1))
}

func (s GameClientMoved) SetY(v int8) {
	capnp.Struct(s).SetUint8(1, uint8(v))
}

// GameClientMoved_List is a list of GameClientMoved.
type GameClientMoved_List = capnp.StructList[GameClientMoved]

// NewGameClientMoved creates a new list of GameClientMoved.
func NewGameClientMoved_List(s *capnp.Segment, sz int32) (GameClientMoved_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[GameClientMoved](l), err
}

// GameClientMoved_Future is a wrapper for a GameClientMoved promised by a client call.
type GameClientMoved_Future struct{ *capnp.Future }

func (f GameClientMoved_Future) Struct() (GameClientMoved, error) {
	p, err := f.Future.Ptr()
	return GameClientMoved(p.Struct()), err
}

type GameClientGarbage capnp.Struct

// GameClientGarbage_TypeID is the unique identifier for the type GameClientGarbage.
const GameClientGarbage_TypeID = 0x991d0e65a6c49290

func NewGameClientGarbage(s *capnp.Segment) (GameClientGarbage, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return GameClientGarbage(st), err
}

func NewRootGameClientGarbage(s *capnp.Segment) (GameClientGarbage, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return GameClientGarbage(st), err
}

func ReadRootGameClientGarbage(msg *capnp.Message) (GameClientGarbage, error) {
	root, err := msg.Root()
	return GameClientGarbage(root.Struct()), err
}

func (s GameClientGarbage) String() string {
	str, _ := text.Marshal(0x991d0e65a6c49290, capnp.Struct(s))
	return str
}

func (s GameClientGarbage) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GameClientGarbage) DecodeFromPtr(p capnp.Ptr) GameClientGarbage {
	return GameClientGarbage(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GameClientGarbage) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GameClientGarbage) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GameClientGarbage) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GameClientGarbage) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GameClientGarbage) Text() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.TextList(p.List()), err
}

func (s GameClientGarbage) HasText() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GameClientGarbage) SetText(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewText sets the text field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s GameClientGarbage) NewText(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// GameClientGarbage_List is a list of GameClientGarbage.
type GameClientGarbage_List = capnp.StructList[GameClientGarbage]

// NewGameClientGarbage creates a new list of GameClientGarbage.
func NewGameClientGarbage_List(s *capnp.Segment, sz int32) (GameClientGarbage_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[GameClientGarbage](l), err
}

// GameClientGarbage_Future is a wrapper for a GameClientGarbage promised by a client call.
type GameClientGarbage_Future struct{ *capnp.Future }

func (f GameClientGarbage_Future) Struct() (GameClientGarbage, error) {
	p, err := f.Future.Ptr()
	return GameClientGarbage(p.Struct()), err
}
