// This file has been automatically generated by capnp-es.
import * as cpnp from "capnp-es";
export const _capnpFileId = BigInt("0xbc17d12a74fd5cc3");
export class Heartbeat extends cpnp.Struct {
  static readonly _capnp = {
    displayName: "Heartbeat",
    id: "ca523d1bb70db70d",
    size: new cpnp.ObjectSize(0, 0),
  };
  toString(): string { return "Heartbeat_" + super.toString(); }
}
