// This file has been automatically generated by capnp-es.
import * as cpnp from "capnp-es";
export const _capnpFileId = BigInt("0xb544471b4cf6fddd");
export class Player extends cpnp.Struct {
  static readonly _capnp = {
    displayName: "Player",
    id: "c8a5b9936b00d9a4",
    size: new cpnp.ObjectSize(8, 2),
  };
  /**
* User ID as UTF8 string
*
*/
  get id(): string {
    return cpnp.utils.getText(0, this);
  }
  set id(value: string) {
    cpnp.utils.setText(0, value, this);
  }
  get name(): string {
    return cpnp.utils.getText(1, this);
  }
  set name(value: string) {
    cpnp.utils.setText(1, value, this);
  }
  get x(): number {
    return cpnp.utils.getInt32(0, this);
  }
  set x(value: number) {
    cpnp.utils.setInt32(0, value, this);
  }
  get y(): number {
    return cpnp.utils.getInt32(4, this);
  }
  set y(value: number) {
    cpnp.utils.setInt32(4, value, this);
  }
  toString(): string { return "Player_" + super.toString(); }
}
export class GameBroadcastConnect extends cpnp.Struct {
  static readonly _capnp = {
    displayName: "GameBroadcastConnect",
    id: "8d79563191b5ff43",
    size: new cpnp.ObjectSize(8, 1),
  };
  _adoptPlayer(value: cpnp.Orphan<Player>): void {
    cpnp.utils.adopt(value, cpnp.utils.getPointer(0, this));
  }
  _disownPlayer(): cpnp.Orphan<Player> {
    return cpnp.utils.disown(this.player);
  }
  get player(): Player {
    return cpnp.utils.getStruct(0, Player, this);
  }
  _hasPlayer(): boolean {
    return !cpnp.utils.isNull(cpnp.utils.getPointer(0, this));
  }
  _initPlayer(): Player {
    return cpnp.utils.initStructAt(0, Player, this);
  }
  set player(value: Player) {
    cpnp.utils.copyFrom(value, cpnp.utils.getPointer(0, this));
  }
  /**
* Connect or disconnect
*
*/
  get connected(): boolean {
    return cpnp.utils.getBit(0, this);
  }
  set connected(value: boolean) {
    cpnp.utils.setBit(0, value, this);
  }
  toString(): string { return "GameBroadcastConnect_" + super.toString(); }
}
/**
* Someone sent a chat message.
*
*/
export class GameBroadcastChat extends cpnp.Struct {
  static readonly _capnp = {
    displayName: "GameBroadcastChat",
    id: "f8ed6301e876b572",
    size: new cpnp.ObjectSize(0, 2),
  };
  /**
* Who, maybe also send as whole player instead?
*
*/
  get name(): string {
    return cpnp.utils.getText(0, this);
  }
  set name(value: string) {
    cpnp.utils.setText(0, value, this);
  }
  /**
* What they sent.
*
*/
  get text(): string {
    return cpnp.utils.getText(1, this);
  }
  set text(value: string) {
    cpnp.utils.setText(1, value, this);
  }
  toString(): string { return "GameBroadcastChat_" + super.toString(); }
}
export class GameBroadcastPlayerMove extends cpnp.Struct {
  static readonly _capnp = {
    displayName: "GameBroadcastPlayerMove",
    id: "8e5205afc0f14fe0",
    size: new cpnp.ObjectSize(0, 1),
  };
  _adoptWho(value: cpnp.Orphan<Player>): void {
    cpnp.utils.adopt(value, cpnp.utils.getPointer(0, this));
  }
  _disownWho(): cpnp.Orphan<Player> {
    return cpnp.utils.disown(this.who);
  }
  get who(): Player {
    return cpnp.utils.getStruct(0, Player, this);
  }
  _hasWho(): boolean {
    return !cpnp.utils.isNull(cpnp.utils.getPointer(0, this));
  }
  _initWho(): Player {
    return cpnp.utils.initStructAt(0, Player, this);
  }
  set who(value: Player) {
    cpnp.utils.copyFrom(value, cpnp.utils.getPointer(0, this));
  }
  toString(): string { return "GameBroadcastPlayerMove_" + super.toString(); }
}
export class GameServerGarbage extends cpnp.Struct {
  static readonly _capnp = {
    displayName: "GameServerGarbage",
    id: "d3f2426b260480f4",
    size: new cpnp.ObjectSize(8, 1),
  };
  /**
* Amount of garbage to send per message
* Probably can't actually send a whole lot here.
*
*/
  get amount(): number {
    return cpnp.utils.getUint32(0, this);
  }
  set amount(value: number) {
    cpnp.utils.setUint32(0, value, this);
  }
  /**
* How many per second
*
*/
  get per(): number {
    return cpnp.utils.getUint8(4, this);
  }
  set per(value: number) {
    cpnp.utils.setUint8(4, value, this);
  }
  /**
* Base of the message
* sha1 (base + per.N)
*
*/
  get base(): string {
    return cpnp.utils.getText(0, this);
  }
  set base(value: string) {
    cpnp.utils.setText(0, value, this);
  }
  toString(): string { return "GameServerGarbage_" + super.toString(); }
}
/**
* List of players
*
*/
export class GameServerPlayers extends cpnp.Struct {
  static readonly _capnp = {
    displayName: "GameServerPlayers",
    id: "aaccfc7400a32fc1",
    size: new cpnp.ObjectSize(0, 1),
  };
  static _Players: cpnp.ListCtor<Player>;
  _adoptPlayers(value: cpnp.Orphan<cpnp.List<Player>>): void {
    cpnp.utils.adopt(value, cpnp.utils.getPointer(0, this));
  }
  _disownPlayers(): cpnp.Orphan<cpnp.List<Player>> {
    return cpnp.utils.disown(this.players);
  }
  get players(): cpnp.List<Player> {
    return cpnp.utils.getList(0, GameServerPlayers._Players, this);
  }
  _hasPlayers(): boolean {
    return !cpnp.utils.isNull(cpnp.utils.getPointer(0, this));
  }
  _initPlayers(length: number): cpnp.List<Player> {
    return cpnp.utils.initList(0, GameServerPlayers._Players, length, this);
  }
  set players(value: cpnp.List<Player>) {
    cpnp.utils.copyFrom(value, cpnp.utils.getPointer(0, this));
  }
  toString(): string { return "GameServerPlayers_" + super.toString(); }
}
/**
* When a client wants to chat.
*
*/
export class GameClientChat extends cpnp.Struct {
  static readonly _capnp = {
    displayName: "GameClientChat",
    id: "92ebca0fa2bbe017",
    size: new cpnp.ObjectSize(0, 1),
  };
  get text(): string {
    return cpnp.utils.getText(0, this);
  }
  set text(value: string) {
    cpnp.utils.setText(0, value, this);
  }
  toString(): string { return "GameClientChat_" + super.toString(); }
}
/**
* When a client moves
* -1, 0, 1
*
*/
export class GameClientMoved extends cpnp.Struct {
  static readonly _capnp = {
    displayName: "GameClientMoved",
    id: "e5874bdd3e613cd0",
    size: new cpnp.ObjectSize(8, 0),
  };
  get x(): number {
    return cpnp.utils.getInt8(0, this);
  }
  set x(value: number) {
    cpnp.utils.setInt8(0, value, this);
  }
  get y(): number {
    return cpnp.utils.getInt8(1, this);
  }
  set y(value: number) {
    cpnp.utils.setInt8(1, value, this);
  }
  toString(): string { return "GameClientMoved_" + super.toString(); }
}
/**
* Garbage Packet
*
*/
export class GameClientGarbage extends cpnp.Struct {
  static readonly _capnp = {
    displayName: "GameClientGarbage",
    id: "991d0e65a6c49290",
    size: new cpnp.ObjectSize(0, 1),
  };
  _adoptText(value: cpnp.Orphan<cpnp.List<string>>): void {
    cpnp.utils.adopt(value, cpnp.utils.getPointer(0, this));
  }
  _disownText(): cpnp.Orphan<cpnp.List<string>> {
    return cpnp.utils.disown(this.text);
  }
  /**
* Maybe use data instead?
*
*/
  get text(): cpnp.List<string> {
    return cpnp.utils.getList(0, cpnp.TextList, this);
  }
  _hasText(): boolean {
    return !cpnp.utils.isNull(cpnp.utils.getPointer(0, this));
  }
  _initText(length: number): cpnp.List<string> {
    return cpnp.utils.initList(0, cpnp.TextList, length, this);
  }
  set text(value: cpnp.List<string>) {
    cpnp.utils.copyFrom(value, cpnp.utils.getPointer(0, this));
  }
  toString(): string { return "GameClientGarbage_" + super.toString(); }
}
GameServerPlayers._Players = cpnp.CompositeList(Player);
